.flake8, .travis.yml, atef/archive_device.py, atef/pyepics_compat.py, atef/tests/conftest.py, atef/tests/test_archived_device.py, conda-recipe/meta.yaml, requirements.txt
Related:  #14
Most importantly:
* Add an "archived device" ophyd Device translator, which allows you to take a given ophyd Device, turn it into an "archived device", and view its state at any given point in time (assuming it has data inside the archive appliance)
* Add an archiver helper which can retrieve archiver appliance data from multiple appliances in a reasonably performant way
And core things required to get to that point:
* Add a PyepicsPV stand-in/base class that allows for easy control over per-PV data that's represented from the ophyd control layer
* Add tools for rewriting device classes to change `EpicsSignal`-related control layer
* Add basic tooling for custom control layers
Pending:
* Some upstream archiver appliance enhancements will be required for control metadata to …
=> ENH: archived device mixin and tooling

MANIFEST.in, atef/grafana.py, atef/tests/conftest.py, atef/tests/hxr_ebd_fee_checkout_helper.json, atef/tests/test_grafana.py
* Grafana dashboard loading tools
- Define dataclasses, let apischema take care of deserialization 
* Very minimal implementation that will load the given dashboard and not much else.
- Would need modification for other panel types, other data sources, etc.
- But this at least provides a structure for extending it, if we were so inclined
* The schema is not well-defined from Grafana, which is apparently an outstanding issue
* TODO: if we're working with ophyd exclusively, need to map PV name -> `happi item name.attribute` ([whatrecord plugin](https://github.com/pcdshub/whatrecord/blob/master/whatrecord/plugins/happi.py) should help here)
* TODO: apischema dep will be picked up with another PR
* TODO: some panel options and other dataclasses are just marked as "dict" or "list"; these are …
=> WIP/ENH: some preliminary tooling for loading grafana dashboards

atef/check.py, atef/tests/test_comparison_device.py
* One possibility for a path forward; fleshed out to the point of working tests (lack of discussion time? why not code!)
* Not entirely sold on this just yet
* This represents a "verbose config" storage, avoiding the ugly-but-terse "attribute to checklist" style that was previously here
* Since we've decided on providing a configuration GUI for v0, I myself am at least less worried about making the format something a human would _want_ to edit (though this form absolutely is something they _could_ edit).
* Some is still not implemented (methods to search the configuration for attributes or PVs or tags)
(for discussion tomorrow, hopefully, @ZLLentz !)
=> REF: rework device/pv config storage

atef/bin/config.py
Add the exception handler from `pydm.exception`, which will display any exceptions we hit in a dialog window instead of simply crashing the app and dumping the exception to terminal.
Use the default handler for now. Later, we may want to expand this similar to what we've done in lucid.
closes #42 
Added a fake error temporarily, pressed the button to cause the error
=> ENH: add the default pydm exception handler

atef/widgets/config.py
The base class for `Comparison` data types is not serializable.
To ensure we don't attempt to serialize a `ConfigurationFile` that contains the base class, stop using it as the default and stop allowing it as an option.
Deleting the widget here also removes the code path that would register `Comparison` as a valid option.
The file cannot be saved if we have an instance of `Configuration` in the data structure.
closes #36 
Interactive saving/loading
N/A
=> BUG: do not allow the user to attempt to save the base Comparison

atef/widgets/config.py
- Fix an issue where we would iterate and extend a list infinitely on startup. I was calling a function meant for adding a new comparison widget instead of just the function meant for setting up an existing comparison.
- Actively create all the ATEF items at startup to fill the whole tree, rather than on an as-needed basis.
closes #49 
Interactively only so far
N/A
=> BUG: Fix issues related to opening files

atef/ui/config_overview_row.ui, atef/widgets/config.py
- Add delete buttons to the top-level overview screen. These are visible for unlocked configurations with empty name fields.
- Make the checklist and comparison delete buttons work properly (by modifying the tree)
- Add docstrings and fill in some more missing docstring info
If we decide that we have too many of any of these, we need to be able to delete them.
closes #32 
Docstrings only
=> ENH: add/finish mechanisms for removing configurations, checklists, and comparisons

atef/ui/config_group.ui, atef/ui/str_list_elem.ui, atef/widgets/config.py
Tag button sizing appears incorrect on macOS.
Closes #41
This should fix it on both macOS/Linux.
Interactively on macOS and psbuild-rhel7 via XQuartz X server
See #41
Psbuild:
=> FIX: tag button sizing

atef/check.py, atef/ui/comp_equals.ui, atef/widgets/config.py
An equals/not equals widget for comparison editing. Both are the same widget, just using a different dataclass type and switching out the equals/not equals symbols.
Works toward #30 
Docstrings only
=> ENH: Equals and NotEquals widgets

atef/qt_helpers.py, atef/ui/happi_device_component.ui, atef/ui/happi_metadata_view.ui, atef/ui/happi_search_widget.ui, atef/ui/ophyd_device_tree_widget.ui, atef/util.py, atef/widgets/config.py, atef/widgets/core.py, atef/widgets/happi.py, atef/widgets/ophyd.py
* Add widget for selection of happi item
* Add widget for selection of component + viewing of live control system status
Closes #59 
Issue + PR
<details>
<summary>Old screenshots</summary>
</details>
=> ENH: happi search tool, ophyd device/component display/selection tool

atef/ui/comp_equals.ui, atef/ui/comp_float_gtlt.ui, atef/widgets/config.py
Add config widgets for the following data classes:
- `Greater`
- `GreaterOrEquals`
- `Less`
- `LessOrEquals`
Includes some code consolidation/deduplication for all of these very similar classes.
Compared to the others, I think these were/will be the simplest to define- there is only one field to represent.
Progress towards #30
Docstrings only
=> ENH: GreaterWidget, LessWidget, OrEquals variants

atef/ui/comp_range.ui, atef/widgets/config.py
Add a widget to manipulate the Range comparison dataclass while providing a helpful visualization of the range.
The visualization will change its colors and update the relative spacing of the thresholds as the user changes them.
I've implemented everything I could think of for the visualization while keeping it simple. Some ideas that I discarded because they sounded annoying:
- logarithmic ranges
- single QPainter instead of multi widgets in a grid
- use the mathematical filled/empty dots on the bounds to show inclusive/not
Continues #30 
The visualization is motivated by a need to disambiguate what exactly the behavior of the checks will be as we manipulate the values here.
Docstrings only
First open:
Sensible settings:
The borders move:
Inclusive:
Inversion:
=> ENH: Range widget

atef/ui/config_group.ui, atef/ui/happi_search_widget.ui, atef/ui/string_list_with_dialog.ui, atef/util.py, atef/widgets/config.py, atef/widgets/happi.py
* Use the happi search widget as a device selector
* Use the device/component widget as an attribute selector
* Select happi items and double-click them or click "choose"/'select" with them selected
* Typing in device names is not fun and error-prone
* Typing in component names is even worse
* Interactively
* PR text, as we do
=> REF/ENH: hook up device list with the happi search tool

atef/bin/config.py, atef/widgets/config.py
Allow for `atef config filename.json` to work
Helpful for command-line usage.
Closes #33
Interactively.
This PR text.
=> ENH: allow filename specification from command-line

atef/ui/comp_view.ui, atef/ui/config_group.ui, atef/ui/config_overview_row.ui, atef/ui/id_and_comp.ui, atef/ui/str_list_elem.ui, atef/widgets/config.py, atef/widgets/core.py, dev-requirements.txt
Original Scope:
Other tweaks:
- Remove extra margins from the two-column sections to give them a little bit more room.
- Remove or hide spacers below device/signal selection widgets to make these widgets take up the whole space instead of half of it as the ui is expanded.
- Refactor the tree navigation components a bit to make it easier to consider the navigation separately from the widgets. This includes the introduction/standardization of `PageWidget` and `link_page`.
- Add a no filename clause at `DesignerDisplay` so I could create a base class that inherits from `DesignerDisplay` without loading a file. This allowed me to step around an issue where `DesignerDisplay` needs to be the last thing before `QWidget` in the `mro` usually so that all the widgets can be created before we start …
=> REF/ENH: navigation improvements

atef/ui/id_and_comp.ui, atef/widgets/config.py
Replace the tag-like editing of PVs with a QListWidget that is edited primarily with a multiline text edit.
When you click the + button, a multiline text edit appears. Anything you put into this box is added to the list.
When you select one or more existing lines and double-click, a multiline text edit appears with the lines you selected. You can add, edit, or remove items as you like. On confirmation the new lines will be compared to the old lines and we'll add or remove items as appropriate.
Usability fix- it's very annoying to edit and browse the PV lists now. This lets you copy paste big lists of PVs if you want.
closes #74 
closes #75 
One oddity: the drag/drop here still needs to be implemented to update the data class. I think this probably affects the …
=> ENH: use a QListWidget and a multiline dialog to edit PV lists

atef/widgets/config.py, atef/widgets/happi.py
* Show happi metadata when selecting devices
* Reuses the Item search/metadata/Component widget and just hides the component selector
* In principle we could keep it visible, it would just slow things down unnecessarily since we wouldn't accept attribute selections there...
* Code mentioned in #70 
* Fixes mistaken `client.__len__` call for a performance increase (`len(client)` implicitly researched the database)
* Re-uses cached metadata instead of hitting the happi client again
Interactively
=> ENH: show metadata in device selection + improve performance

atef/widgets/config.py
Check that we are dealing with a line edit in our line edit event filter before proceeding to the checks and style updates.
There is an event filter on some of our edit fields that handles things like changing style when the user selects/deselects the widget. This is only installed on compatible object types, but it can also be called on generic `QWidget` objects that are suspiciously named `line_edit` after the line edit has been removed/cleaned up. You see an unimportant error message when removing some of these objects since `QWidget` doesn't have a `text` attribute, which is checked during this filter. The application continues to run as normal, since the only thing skipped is updating the style of a removed widget, but the error popup is annoying and potentially confusing.
I found …
=> BUG: fix issue with running event filter after cleanup

atef/ui/config_group.ui, atef/ui/id_and_comp.ui, atef/widgets/config.py
Add scrollbars to the two sections where we can add large numbers of sub-items.
Otherwise, the gui just expands relentlessly as we add items.
closes #103 
Will include in the release notes
From an empty config, here's me jamming the "add checklist" button:
A look at the demo config which doesn't overflow the scroll limit of the default size on my screen:
=> ENH: add scrollbars to comparison list and checklist list, adjust style

atef/bin/check.py, atef/check.py
Before, in a slightly-modified local test file (with admittedly nonsensical comparisons!):
```
✔ Success state settings (Check state settings)
├── ✔ Success: AT2L0:XTES:MMS:19:STATE:10:VELO < 1
└── ✔ Success: AT2L0:XTES:MMS:19:STATE:10:ACCL < 1
```
After:
```
✔ Success state settings (Check state settings)
└── Good vacuum checklist
└── Good vacuum comparison
├── ✔ Success: AT2L0:XTES:MMS:19:STATE:10:VELO < 1
└── ✔ Success: AT2L0:XTES:MMS:19:STATE:10:ACCL < 1
```
```
❌ Error state settings (Check state settings)
└── Good vacuum checklist
└── Good vacuum comparison: Make sure we have some level of vacuum everywhere
├── ❌ Error: AT2L0:XTES:MMS:19:STATE:10:VELO < 1: value of 2.0
└── ✔ Success: AT2L0:XTES:MMS:19:STATE:10:ACCL < 1
```
Closes #109 
Interactively, so far
Issue, discussion, and PR …
=> REF/ENH: track + display config/checklist/comparison/id in prepared comparisons

atef/widgets/config.py
When switching between locked & unlocked states for the overview name/description, the background color changes to white to indicate that the widget is editable. On dark themes this makes it unreadable.
On dark themes, the text would become unreadable when switching between locked and edit mode for the overviews.
Tested by clicking lock/unlock
n/a
Unlocked editing. Before this change, the background color of the QLineEdits would be pure white. 
Locked
=> ENH: Restore correct background color when locking/unlocking edits

atef/widgets/happi.py, atef/widgets/ophyd.py
Use row selection mode in the happi and ophyd table views instead of the individual table cell mode.
Row selection mode in these table views makes more sense since the data is related to the rest of the row. 90% of the motivation here is personal preference though, @klauer indicated that row selection mode seemed better too, so I'm not alone in this regard.
Tested by clicking around the table views.
Selection by rows!!!
=> ENH: use row selection mode in Ophyd and Happi table views

atef/widgets/config.py, atef/widgets/happi.py, atef/widgets/ophyd.py
This PR adds various context menus to atef. The Happi, Ophyd and string list widgets all got extended context menus. 
For the `HappiSearchWidget`, I added an "Add device" entry to the context menu that emits the `happi_items_chosen` signal. In atef, that means you can right click a device and "Add device" instead of double clicking it to add it to the device list.
For `OphydDeviceTableView`, a context menu helper was added, which is used to create the base `QMenu` that the standard table view actions are added to. `OphydDeviceTableWidget` adds a context menu helper to display the same menu that's displayed when you click the `Select` button at the bottom.
`StringListWithDialog` got a simple context menu that has "Copy" and "Remove" actions. 
Context menus are just more intuitive and …
=> ENH: Context menus for Happi, Ophyd and string list widgets

.pre-commit-config.yaml, atef/tests/test_archived_device.py
Skips lightpath mixin classes that subclass device, but cannot be simply subclassed, allowing tests to pass.
Now possible thanks to https://github.com/pcdshub/pcdsdevices/pull/1077
closes #133 
This will hold up ci until it's merged, and is a small enough fix to push through
tests pass locally
This PR
=> TST: skip lightpath mixins in test_switch_control_layer

atef/tests/test_archived_device.py, atef/ui/archive_viewer_widget.ui, atef/ui/config_window.ui, atef/ui/name_desc_tags_widget.ui, atef/ui/ophyd_device_tree_widget.ui, atef/widgets/archive_viewer.py, atef/widgets/config/data.py, atef/widgets/config/page.py, atef/widgets/config/utils.py, atef/widgets/config/window.py, atef/widgets/ophyd.py, atef/widgets/procedure.py, conda-recipe/meta.yaml
Adds an archive appliance viewer widget to help during check creation.  Leverages PydmArchiverTimePlot
Includes neat features (read: time sinks) like:
- a neat table view that holds pv curve information (symbol, color, etc.  More to come)
- basic `archapp.EpicsArchive` validation on PV input
- integration with existing context Ophyd/Happi device context menus 
#69 
closes #130 along the way
interactively 
Lots of comments as I learn more about qt
this PR. 
(Opening from the happi/ophyd component selector)
(opening from main window)
(opening from comparison page, opens all signals related to the comparison)
Double clicking on items in the table brings up edit windows
color picker: 
symbol combobox
=> ENH: add archive viewer widget

.github/workflows/init_gha.yml
A minimal gha job (I think) to initialize actions for this repository
We can't run actions in pull requests if gha has not been run in this repository before.  This should be removed in a future PR.
N/A
Here
=> BLD: simple dummy action

atef/bin/check.py, atef/check.py, atef/config.py, atef/procedure.py, atef/report.py, atef/result.py, atef/tests/configs/active_test.json, atef/tests/conftest.py, atef/tests/test_comparison.py, atef/tests/test_comparison_device.py, atef/tests/test_comparison_tools.py, atef/tests/test_configuration.py, atef/tests/test_procedure.py, atef/tools.py, atef/widgets/config/data_active.py, atef/widgets/config/page.py, atef/widgets/config/run_active.py, atef/widgets/config/run_base.py, atef/widgets/config/utils.py, atef/widgets/config/window.py
- Refactors the `Result` fields and and `.run()` methods for active checkout dataclasses into `Prepared*` procedure step dataclasses
- Moves the `Result` dataclass and related helpers into its own submodule.  Refactors accordingly
- Updates window and RunTree logic to reflect these changes
- Adds timestamp field to `Result` dataclass.  This field does not need to be specified at instantiation, and will be auto-filled.  This will also be ignored during comparisons between `Result` objects
After some slack conversations, we decided that it was best to keep any transient information separated from the checkout specification.  This makes active checkouts mirror the structure of passive checkouts.  
It is expected that there will be information worth holding onto while running the checkout. …
=> MNT: refactor active checkouts to have Prepared variants

atef/bin/config.py
Allows Qt command line arguments to be passed through on the command line. Prior to this PR specifying `-style` (or anything else `QGuiApplication` can accept) wasn't possible without argparse complaining.
`-style` is handled specially and will validate against currently available styles, and default to `fusion` on OSX (as per #154).
Closes #154
Qt styling is somewhat operating system specific, which can lead to issues like described in #154. Sometimes it's also desirable to use a different platform plugin or stylesheet. For the most part, these command line arguments are an alternative to envvars Qt also understands.
Tested locally, should work on all systems.
`atef config -style windows`:
=> ENH: allow Qt args on the command line

atef/cache.py, atef/check.py, atef/config.py, atef/procedure.py, atef/qt_helpers.py, atef/tests/configs/active_test.json, atef/tests/test_widgets.py, atef/ui/action_row_run_widget.ui, atef/ui/action_row_widget.ui, atef/ui/add_row_widget.ui, atef/ui/check_row_run_widget.ui, atef/ui/check_row_widget.ui, atef/ui/pv_configuration_page.ui, atef/ui/set_value_edit_widget.ui, atef/ui/set_value_run_widget.ui, atef/ui/step_page.ui, atef/ui/target_entry_widget.ui, atef/widgets/config/data_active.py, atef/widgets/config/data_base.py, atef/widgets/config/page.py, atef/widgets/config/run_active.py, atef/widgets/config/run_base.py, atef/widgets/config/utils.py, atef/widgets/config/window.py, atef/widgets/ophyd.py, atef/widgets/utils.py, docs/source/upcoming_release_notes/159-enh_set_value.rst, pyproject.toml
Adds a step called `SetValueStep`, for setting values to signals/components, then running a set of comparisons.  Actions are stored as a list of target-value dataclasses, and checks are stored as a list of target-comparison dataclasses.  Targets can be specified as either a device - attr combination or raw PV string.   
Along the way:
- adds `TableWIdgetWithAddRow`, a subclass of QTableWidget that includes a `AddRowWidget`. This add row contains a button for adding rows of a specified widget.  (for better space efficiency)
- gets overly fancy with signal/component selectors
- adds support for ProcedureSteps that also contains checks, I imagine this will become more common in the future
- Fixes type hint parsing in QDataClassBridge acfe193
- adds a busy cursor decorator and puts it in a …
=> ENH: add a Set-Value active checkout step

atef/qt_helpers.py, atef/widgets/config/data_passive.py, atef/widgets/happi.py, docs/source/upcoming_release_notes/168-bug_types_etc.rst
Fixes a smattering of bugs I found while messing around with the GUI
* cast values read from the config to a string in AnyValue widget, closes #165 
* Pick up sequences in QDataclassBridge, closes #163 
* As a consequence transitioning from hard-coded hint recognition, this bug was created.
* Sets the comparison widget type based on the loaded datatype.  closes #78 
* Allows device selection via double-click in the HappiSearchWidget tree-view 
* Previously there was no way to select a device from this view (no right-click context menu, etc)
Bug free please
Interactively
This PR, and the issues they reference
=> BUG: fix type handling, etc

atef/widgets/config/utils.py
Typing fix for bounds of `QIcon.paint`. 
This was raising a type error in my conda environment which I setup per the README. I'm not using the pcds conda environment though. I'm thinking this might be related to having Qt6 installed on my system. It seems to absolutely require `int` instead of `float` or another numeric type for `QRect` and `QSize`.
Tested locally in a conda environment with python 3.10.11.
Not documented anywhere
=> FIX: use integers for rect bounds with QIcon.paint

.github/PULL_REQUEST_TEMPLATE.md, atef/widgets/config/data_active.py, atef/widgets/utils.py, docs/source/upcoming_release_notes/170-mnt_bgd_signal.rst
- Places a `signal.wait_for_connection` call into a background thread
- Makes the `BusyCursorThread.raised_exception` actually expect to emit an Exception
Closes #170 
Interactively
This PR
=> MNT: wrap signal connection check in BusyCursorThread

atef/qt_helpers.py, atef/report.py, atef/tests/test_widgets.py, atef/widgets/config/data_active.py, atef/widgets/config/window.py, atef/widgets/ophyd.py, docs/source/upcoming_release_notes/175-mnt_sig_imp.rst
Honestly a grab-bag of various issues.
* Adds Enum support to the `SetValueStep`'s actions, closes #174 
* (attempts to) Fix optional type hint handling in `QDataclassBridge`
* Differentiates between read and write (set) PV's in `OphydDeviceTableView` -thing.  closes #173 
* Wraps signal.get call used for setting input type validators in BusyCursorThread
Currently, `QDataclassBridge` handled optional field type hints by simply making a `QDataclassValue` with `object` as the expected type.  This worked as long as only the `changed_value` signal was used, but failed for hints such as `Optional[List[str]]`, since those often started looking for `QDataclassList` signals (`added_value`, `changed_value`, etc)
Report used to fail if users didn't add a name to their steps/checks.  Now we handle …
=> MNT: Generally improve things related to signals, touch up reports default behavior

atef/ui/config_window.ui, atef/ui/landing_page.ui, atef/widgets/config/window.py, docs/source/upcoming_release_notes/176-gui_landing_page.rst
- Replace the welcome dialog with a landing tab, closes #151 
- Set up close buttons, and move run-toggle to reveal it
I grow tired of users losing the welcome splash in their array of 6 monitors and complaining atef is frozen.
Interactively
This PR
=> GUI: Replace welcome dialog with welcome tab, enable closable tabs

atef/report.py, docs/source/upcoming_release_notes/183-bug_report_val.rst
Fixes a quick bug, the observed value could be False-y (e.g. 0), and skip the whole block.  also cleans up try blocks
Make sure reports always report actual observed values 
Interactively 
This PR
=> BUG: fix observed value report output

atef/tests/test_widgets.py, atef/widgets/config/run_base.py, atef/widgets/config/window.py, docs/source/upcoming_release_notes/186-bug_pre_tag.rst
Fixes up a couple things before tagging
- Refreshes the Result icons on paint events, so they should update every time they are brought into focus
- Improves handling when a mode switch (edit <-> run) fails.  Previously this would fail but the toggle would switch, requiring a program restart
I was hoping to fix more bugs but I gave myself a deadline and I can't reproduce the bugs I saw when Tong was running.  🤷 
Tossing Exceptions in the middle of the switch_mode block, but otherwise just running the test suite
This PR
=> MNT: Better mode switch handling, icon refresh

atef/annotated_plans.py, atef/enums.py, atef/plan_utils.py, atef/procedure.py, atef/tests/conftest.py, atef/tests/profiles/user_group_permissions.yaml, atef/tests/sample_plans.py, atef/tests/test_plan_utils.py, atef/tests/test_procedure.py, atef/widgets/config/plan_builder.py, conda-recipe/meta.yaml, docs/source/upcoming_release_notes/193-enh_plan_step.rst, requirements.txt
Adds a step for specifying and running a bluesky step as part of an atef checkout.  Adopts bluesky_queueserver's api for specifying and preparing plans to run, with the eventual dream of being able to support sending plans to a queueserver.  (Whether or not this actually happens, I think their way of handling plans and annotations is worth adopting)
There's a lot that will go into this.  I will enumerate and organize tasks below, and update the list as I decide whether or not to work on any given task.  "completion" is transient at best, as I end up having to re-work previously completed items during development
[Ever-evolving dataclass diagram](https://docs.google.com/drawings/d/1ch44p8pCC4M1C4FldKMPHAMLK_GEFozzgzi6mbdo3Hw/edit?usp=sharing)
I've been told to shift my focus to templated …
=> ENH: Add a bluesky-plan step

atef/procedure.py, atef/tests/conftest.py, atef/tests/test_find_replace.py, atef/tests/test_widgets.py, atef/ui/config_window.ui, atef/ui/fill_template_page.ui, atef/ui/find_replace_row_widget.ui, atef/ui/find_replace_widget.ui, atef/ui/landing_page.ui, atef/ui/template_edit_row_widget.ui, atef/widgets/config/data_active.py, atef/widgets/config/find_replace.py, atef/widgets/config/page.py, atef/widgets/config/plan_builder.py, atef/widgets/config/utils.py, atef/widgets/config/window.py, atef/widgets/utils.py, docs/source/upcoming_release_notes/198-enh_fill_template.rst
- Implements atef-specific find and replace functionality
- adds a basic find-and-replace widget
- finish up / clean up widget button functionality
This stems from a request for templated checkouts, which boils down to having find-and-replace functionality.  A naive find-and-replace on the json could touch file/field names, and is rather difficult to inspect.  
My intention is to make the future "fill template" step / tool wrap this functionality, possibly with some extra visualization or streamlining buttons.  A sample checkout could be run through this tool and and "filled" as is with this tool, I imagine
(In reality I implemented the simple find-and-replace helpers, tried making it more robust, and a week later ended up here.)
Creating a step that fills templates mid-checkout is a …
=> ENH: find and replace functionality

atef/tests/test_widgets.py, atef/ui/multi_mode_value_edit.ui, atef/widgets/config/data_active.py, atef/widgets/config/utils.py, docs/source/upcoming_release_notes/208-mnt_sci_double_spinbox.rst
Creates a ScientificDoubleSpinBox for use in MultiModeValueEdit
closes #207 
The standard DoubleSpinBox has limited significant digits, and will coerce values with more sig figs.  With the standard QSpinBox we arbitrarily chose a number of decimals (4), which prevented more precise values in comparisons.
I can't really take credit for this implementation, but I did make it qt5 compatible (why does `validate` return a tuple[state, str, int]?  Why can't it just take the validation status? 🤔 This apparently changed a lot over qt versions)
Reported by Rizheng.
EnumStrings weren't initializing properly in some cases (initializing to an empty list), causing the widget to be effectively non-operational.  Added a wait_for_connection call, which is added to a BusyCursorThread. …
=> ENH: add ScientificDoubleSpinBox and use it in MultiModeValueEdit

atef/ui/config_window.ui, atef/widgets/config/data_passive.py, atef/widgets/config/page.py, atef/widgets/config/window.py, docs/source/upcoming_release_notes/213-mnt_bug_misc_fixes.rst
- `RangeWidget`'s visualizations update a bit more frequently, and also the label text actually updates. Closes #212 
- Adds a menu option to open the welcome tab, since people like it.  Closes #201 
- Properly shows an error message box when a file can't be opened.  Closes #202 
- Removes child `AtefItem` from a ProcedureStep when it's changed from the specific-step-combobox.  Closes #195 
- Allow tolerances to be `None` in Equals comparison.  Modifies the line-edit setup to allow null values ('', None) when casting the line edit value.  Closes #128 
An assortment of fixes because I didn't want to work on anything big but still wanted to be a bit productive
interactively
This PR
=> MNT/BUG: Misc fixes

atef/procedure.py, atef/tests/test_widgets.py, atef/widgets/config/data_active.py, atef/widgets/config/find_replace.py, atef/widgets/config/utils.py, atef/widgets/config/window.py, atef/widgets/utils.py, conda-recipe/meta.yaml, docs/source/upcoming_release_notes/214-tst_qt_teardown.rst, requirements.txt
Attempting to fix some intermittent test suite failures.  The crux of the difficulty here is that the suite consistently passes locally, failing only intermittently on GHA CI
- Uses / vendors Typhos' `WeakPartialMethodSlot` for applying callbacks within `ActionRowWidget`
- In one case opted to try making the slots submitted to `BusyCursorThread` actual methods, rather than dynamically created functions
- When pcdsutils is updated, we can remove the vendoring here and rely on pcdsutils' versino
- There is still a very rare test suite failure, but I cannot reproduce it enough to address it.  For the curious, it seems to fail at [`get_curr_value`](https://github.com/pcdshub/atef/actions/runs/6407993392/job/17396405838#step:17:737), the epics-get portion of `ActionRowWidget`
- While this is …
=> TST: Attempted test suite fixups

atef/check.py, atef/config.py, atef/reduce.py, atef/tests/test_comparison.py, docs/source/upcoming_release_notes/219-mnt_enum_check.rst
When checking against an enum signal, check against both the integer and string value if needed.
Also ignore tolerances unless comparing against a number
closes #200 
closes #220 
Interactively, and a test case has been added. 
This PR
=> MNT: make enum checks more robust

atef/procedure.py, atef/qt_helpers.py, atef/report.py, atef/tests/configs/active_test.json, atef/tests/test_comparison.py, atef/tests/test_walk.py, atef/ui/results_summary.ui, atef/ui/run_config_tree.ui, atef/walk.py, atef/widgets/config/data_active.py, atef/widgets/config/result_summary.py, atef/widgets/config/run_active.py, atef/widgets/config/run_base.py, atef/widgets/config/utils.py, atef/widgets/config/window.py, docs/source/upcoming_release_notes/221-enh_status_out.rst
- Refactors "walk" helpers to a separate submodule, because I was getting confused and caught myself re-inventing the wheel
- Use ConfigTreeModel to show results in the tree view during run-mode (closes #146)
- Adds a "Results Summary" widget that shows a filterable view of checkout results, as well as a plaintext csv view for copying etc
Also jira [ECS-1380](https://jira.slac.stanford.edu/browse/ECS-1380?jql=project%20%3D%20ECS%20AND%20component%20%3D%20ATEF)
Because the next thing I intend to do is rework how the page loading is done (for performance reasons), I expect the way trees are constructed to change significantly.  There's a couple places where I left todos to circle back on after I've settled on an approach.  
Interactively, a couple tests added
This PR
=> ENH: Improve status output

atef/config.py, atef/tests/test_page.py, atef/ui/device_configuration_page.ui, atef/ui/paged_table.ui, atef/ui/pv_configuration_page.ui, atef/ui/tool_configuration_page.ui, atef/util.py, atef/widgets/config/page.py, atef/widgets/config/paged_table.py, atef/widgets/config/window.py, conda-recipe/meta.yaml, docs/source/upcoming_release_notes/226-enh_paged_table.rst, requirements.txt
Replaces the existing `QTableWidget` + `cellWidget` combination with a `PagedTableWidget`, for splitting up rows into pages.
Previously, all the row widgets were created on PageWidget creation.  This can lead to long loading times that aren't remedied by the previous lazy page loading effort. 
This may seem a bit complicated, but should be the proper way to let qt handle construction and destruction of row widgets.  There was some complexity involved when hooking up buttons / slots inside these row widgets, since widgets can be created or destroyed at any time.  This means saving connection slots in a way that can be re-initialized at will.
I made an effort to keep the existing widgets and their functionality.
interactively
This PR
=> ENH: Add and apply PagedTableWidget

docs/source/upcoming_release_notes/228-enh_pmgr_check.rst, scripts/pmgr_check.py
A simple script to grab a config from pmgr and write an atef check to verify the values
https://jira.slac.stanford.edu/browse/ECS-1350
I'm honestly not sure if this is the minimal amount of information needed to grab a configuration, but this is similar to the pcdsdevices pmgr usage, and seems to work.
I ran the script, wrote a checkout, and ran it properly
This PR, and some docstring
=> ENH: add pmgr-to-atef-check script

atef/bin/main.py, atef/bin/scripts.py, atef/scripts/converter_v0.py, atef/scripts/pmgr_check.py, atef/tests/conftest.py, docs/source/upcoming_release_notes/229-mnt_pmgr_cli.rst
Refactors the scripts in the separate "scripts" folder into a sub-subcommand, so people can use them without knowing the exact path
If someone wanted to use these scripts before, they'd have to do call the precise path:
```
python ./atef/scripts/converter_v0.py [args, kwargs]
```
This seems less than accessible, so I wanted to fold them into the atef CLI.  We now scan the scripts submodule, and each sub-sub-module gets its own `atef scripts` subsubcommand
<details><summary>Example CLI invocations</summary>
<p>
```bash
$ atef -h
usage: atef [-h] [--version] [--log LOG_LEVEL] {check,config,scripts} ...
`atef` is the top-level command for accessing various subcommands.
Try:
$ atef check --help
$ atef config --help
$ atef scripts --help
positional arguments:
{check,config,scripts}
Possible …
```
=> MNT: Refactor scripts into `atef scripts` subcommand

atef/widgets/config/window.py, docs/source/upcoming_release_notes/231-bug_segfault_deleteLater.rst
Remove `deleteLater()` and `setParent(None)` calls from cached widget deletion process, as they seem to cause segfaults and are not strictly necessary...
closes #230 
Interactively, I need to add (better) tests though (for a followup)
My interactive testing focused on making sure widgets were actually being deleted by garbage collection, despite not explicitly requesting it.  To do this I held a weakref to widgets that were popped from the cache, and observed that these weakrefs weren't piling up as I loaded and popped widgets.   This could be made more empirical of course, I'll hopefully fix that soon.
This PR
=> BUG: remove deleteLater() and setParent(None) calls

atef/tests/test_widgets.py, atef/widgets/config/window.py, docs/source/upcoming_release_notes/233-mnt_avoid_selectionModel.rst
Replaces selectionModel calls, use `QTreeView.setCurrentIndex()`.  
Closes #232 , but also allows me to write (slightly) better tests for #231 
Interactively, but also I added a test.
This PR
=> MNT: remove selectionModel calls, use `QTreeView.setCurrentIndex()`

atef/widgets/config/utils.py, docs/source/upcoming_release_notes/234-bug_mmve_late_cb.rst
Makes the `BusyCursorThread` called in `MultiModeValueEdit` more tolerant of widgets being garbage collected while EPICS is timing out
closes #234 
In summary, aspects of `MultiModeValueEdit` (`MMVE`) call EPICS, and if we're thumbing quickly through the pages, we can pop the parent page from the cache and delete it before the connection times out.   The callback would then fire, and cause ATEF to throw an error. 
We just catch those and ignore it if this is the case.
interactively, and by removing the cache limitation in `test_open_all_pages`
This PR
=> BUG: Fix widget-deleted errors in `MultiModeValueEdit`

atef/find_replace.py, atef/tests/test_find_replace.py, atef/widgets/config/find_replace.py, docs/source/upcoming_release_notes/237-mnt_sep_find_replace.rst
Separates the find-replace logic and dataclasses from the widgets that display them.
No functional changes in this PR
In preparation for future explicit templating steps, and also just something that should be done anyway.
The test suite still works 🎉 
This PR
=> MNT/REF: separate find replace logic from widgets

atef/config.py, atef/find_replace.py, atef/procedure.py, atef/tests/conftest.py, atef/tests/test_configuration.py, atef/tests/test_procedure.py, atef/widgets/config/find_replace.py, docs/source/upcoming_release_notes/238-enh_template_step.rst
Adds a configuration/step for finding/replacing objects in an existing checkout, and running it.  GUI elements will be added in a separate effort
A frequently requested feature.  This is the first part of this
Much refactoring needed to be done here, for a couple of reasons:
- The existing `FindReplaceAction` was not serializable
- The callables used to encapsulate replacement actions could not be stored in a json
- I created a more specific, but less flexible version (`RegexFindReplace`) that gets converted to the existing `FindReplaceAction` before application.
- A bunch of refactoring was needed to still type hint while preventing circular imports.  
Fun note: using `asyncio.run(config.compare())` in the test suite seemed to sometimes "kill the main thread", and would cause later …
=> ENH: Add Template Configuration and Step

atef/find_replace.py, atef/ui/fill_template_page.ui, atef/ui/template_edit_row_widget.ui, atef/widgets/config/data_active.py, atef/widgets/config/find_replace.py, atef/widgets/config/page.py, atef/widgets/config/run_active.py, atef/widgets/config/run_base.py, atef/widgets/config/utils.py, atef/widgets/config/window.py, docs/source/upcoming_release_notes/239-enh_ref_fill_template_page.rst
- Adds a staging area to `FillTemplatePage`, to be more clear about which changes are being queued for application
- Refactors various helpers and widgets to support this
- Adds tree-view that highlights closest tree-item when a row detail is examined
In looking into reusing `FillTemplatePage` for templated checkouts, it became clear that the page needed a refactor
- If we were to serialize actions, we would need some way to display those queued actions.
- Previously, `FillTemplatePage` would maintain an internal "all actions" list and a user could apply them gradually.  This made the current state of the loaded checkout ambiguous (had we applied changes yet?)
- Edit actions (`FindReplaceAction`) saved in a templated checkout would need to be loaded without knowledge of the search query …
=> ENH/REF: Modify FillTemplatePage to have staging area

atef/config.py, atef/exceptions.py, atef/find_replace.py, atef/procedure.py, atef/tests/test_page.py, atef/ui/template_group_page.ui, atef/ui/template_run_widget.ui, atef/widgets/config/find_replace.py, atef/widgets/config/page.py, atef/widgets/config/run_active.py, atef/widgets/config/window.py, docs/source/upcoming_release_notes/241-enh_template_gui.rst
- Adds `TemplateConfigurationPage` and `TemplateRunWidget` for editing and running Template-steps in the atef config gui.
- Plugs `TemplateStep`/`TemplateConfiguration` into the various "maps" we have littered around the repo.
- Plugs a few holes from previous PRs.  (There should be no more holes, since this should be the last Template step PR)
In a bit of laziness / DRY, I've used the same pages for both the active and passive checkout cases.  
There's a bit of finicky business when it comes to preparing checkouts with template-steps.  As is, the step/config fails to prepare if the file is invalid.  This will cause the entire page to fail.  In my initial formulation this was the proper thing to do, but I'm starting to think it's not transparent enough about its failure mode. …
=> GUI/ENH: add template steps to passive and active checkout GUI

atef/bin/check.py, conda-recipe/meta.yaml, docs/source/upcoming_release_notes/248-enh_cli_report.rst, requirements.txt
Adds the option to save a report after running a passive checkout from the CLI
I promised this in a meeting earlier today and it didn't exist
Interactively: `atef check checkout.json -r report.pdf`
This PR, and in some docstrings
=> ENH: add report output option to atef check cli

atef/report.py, docs/source/upcoming_release_notes/246-enh_template_report.rst
Adds report output for template steps/reports
More refining to do, but the start is here
Reports are basically the reason atef exists.
We probably want some better reprs for the `RegexFindReplace` classes.
interactively
This PR
=> ENH: add support for template steps/configs in reports

conda-recipe/meta.yaml, docs/source/releases.rst
Specify bluesky-base in conda-recipe
Fix broken conda builds, where bluesky --> matplotlib --> qt6-main
Surely the CI passes 
this PR
=> BLD: specify bluesky-base in conda recipe

conda-recipe/meta.yaml, docs/source/releases.rst, requirements.txt
see title
I stg if I have to pin another thing
CI please bless me 🙏 
This PR
=> BLD: pin matplotlib<=3.9.0, avoid qt6 deps

atef/widgets/config/data_active.py, atef/widgets/ophyd.py, docs/source/upcoming_release_notes/254-bug_action_writepv.rst
when selecting a ophyd device/signal, the original behavior would store both the PV name and device-attribute pair.  If the device signal has a separate write pv, we weren't saving that properly
Adjust this to save the `_setpoint_pv` if available, then the `pvname` after.  (ophyd signals have no write_pv attribute explicitly 🤷 )
A bug Christian found while using atef and templates
Interactively
This PR
=> BUG: store _setpoint_pv in Target where possible

atef/widgets/config/data_active.py, atef/widgets/config/utils.py, docs/source/upcoming_release_notes/259-mnt_timeout_nav.rst
- increase the limit on spinboxes generated from MultiInputFormDialog, in response to a request that set-value-step timeouts not be limited to 99s (we have very slow motors)
- navigate BACK to the parent page when creating a new check in SetValueStep
- This negates the default behavior of StepPage, which selects new items when they are created. 
- Because SetValueStep initialized a row/new item without setting a PV, this resulted in extraneous navigation back to the parent page to set the PV, then back to the details to set the comparison information
- Hacky but I'm too lazy to figure out a better way
Bug reports from @c-tsoi 
Interactively.  Test suite still passes
This PR
=> MNT: increase timeout limits (limits on all form spinboxes), prevent aggressive navigation

atef/tests/test_commandline.py, docs/source/upcoming_release_notes/261-mnt_cli_sub.rst
Fixes broken (though passing) smoke tests for the atef cli subcommands
I was copying the pattern to a different repo and found it didn't work. 
Previously we were patching `sys.argv` to hold the arguments we wanted to invoke the cli with, but these did nothing if the actual command "atef" wasn't included.  Without "atef" in the argv list, we would just see what happens if we invoke "atef" with no arguments.  
By un-suppressing the output in pytest and making sure each sub-command's help message got printed properly
This PR
=> MNT: fix broken cli subcommand smoke tests

atef/widgets/config/data_active.py, atef/widgets/config/find_replace.py, atef/widgets/config/run_active.py, atef/widgets/config/window.py, conda-recipe/meta.yaml, docs/source/upcoming_release_notes/262-bld_unpin_numpy.rst, requirements.txt
Try unpinning numpy, now that more upstream packages are compatible
new environment time?
CI
This PR
=> BLD: unpin numpy, xraylib now compatible

atef/tests/test_widgets.py, atef/widgets/config/utils.py, docs/source/upcoming_release_notes/268-bug_spinbox_max.rst
- Adjusts the integer spinbox maximum setting to avoid overflow.  Adjusts the float spinbox to match, for symmetry
This has apparently been a bug for months, but nobody tried to build a report so we never ran into it.
The double spinbox is fine since doubles have a larger range
Bug was reported by Tong today
Interactively, and a smoke test has been added
This PR
=> BUG: fix spinbox maximum setting
